### PR TITLE
adding birdcam data and analysis/folder reorg

### PR DESCRIPTION
**Pull request by stevelongmire**

### CODE REVIEW

**Comment by billpine** [comment]
Hi, I think this has to be reviewed by Steve Beck before the pull request can be merged.

**Comment by stevelongmire** [comment]
Ah okay, I thought I sent it to him for review as well. I haven't pulled to a master branch yet
________________________________

**Comment by sbeck1** [comment]
Yes, I sat with Steven when he submitted the request to add bird cam data and Mel suggested I should be the reviewer.  I asked him to use the folder structure on the tdrive.  So Monday I'll merge and finish cleaning up the bird repository, per my other email.   
________________________________________

**Comment by billpine** [comment]
Ok sounds good.

On Dec 16, 2018, at 6:48 AM, sbeck1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, I sat with Steven when he submitted the request to add bird cam data and Mel suggested I should be the reviewer. I asked him to use the folder structure on the tdrive. So Monday I'll merge and finish cleaning up the bird repository, per my other email.
________________________________________

**Comment by stevelongmire** [comment]
Awesome, thanks Steve. Glad it worked
________________________________

**Pull request merged**
